name: build_and_publish_docs

on:
  push:
    branches:
    - dev
    - master
    - test/**
    tags:
    - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
    - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/master' }}

jobs:
  publish:
    name: build and publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.6'

      - name: setup poetry and install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          python -m poetry install --with tutorials,docs --all-extras --no-ansi --no-interaction

      - name: test actions/checkout_v4 (remove this before merging PR)
        run: |
          git branch
          git status
          echo "${{ github.head_ref || github.ref_name }}"

      - name: save docs version into a variable
        run: |
          echo "DOC_VERSION=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV

      - name: build documentation
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_BOT_USERNAME: ${{ secrets.TG_BOT_USERNAME }}
          DOC_VERSION: ${{ env.DOC_VERSION }}
          VERSION_SWITCHER_STARTING_TAG: ${{ env.VERSION_SWITCHER_STARTING_TAG }}
          VERSION_SWITCHER_TAG_BLACKLIST: ${{ env.VERSION_SWITCHER_TAG_BLACKLIST }}
          VERSION_SWITCHER_TAG_WHITELIST: ${{ env.VERSION_SWITCHER_TAG_WHITELIST }}
        run: |
          python -m poetry run poe docs

      - name: remove jekyll theming
        run: touch docs/build/.nojekyll

      - name: set up mutex
        uses: ben-z/gh-action-mutex@v1.0.0-alpha.9

      - name: deploy website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/build/
          target-folder: ${{ env.DOC_VERSION }}
          clean: True

      - name: copy version switcher for updating it
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master' }}
        run: |
          mkdir docs/build/switcher/
          cp docs/build/_static/switcher.json docs/build/switcher/switcher.json

      - name: update version switcher
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/build/switcher/
          clean: False

      - name: print link to the documentation
        run: |
          echo "https://deeppavlov.github.io/chatsky/${{ github.head_ref || github.ref_name }}"
